apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-hello
  labels:
    app: apache-hello
  annotations:
    # ArgoCD Image Updater will track ONLY this image repo
    argocd-image-updater.argoproj.io/image-list: apache=docker.io/anusha292/apache-hello

    # Use digest strategy → works with timestamp tags perfectly
    argocd-image-updater.argoproj.io/apache.update-strategy: digest

    # Use docker registry pull secret
    argocd-image-updater.argoproj.io/apache.pull-secret: pullsecret:docker-creds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-hello
  template:
    metadata:
      labels:
        app: apache-hello
    spec:
      imagePullSecrets:
        - name: docker-creds
      containers:
        - name: apache
          # Placeholder only — updater will replace this automatically
          image: docker.io/anusha292/apache-hello:v0.0.0
          ports:
            - containerPort: 80
