apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-hello
  labels:
    app: apache-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-hello
  template:
    metadata:
      labels:
        app: apache-hello
    spec:
      imagePullSecrets:
        - name: docker-creds

      containers:
        - name: apache
          # ArgoCD Image Updater WILL update this tag automatically in Git
          image: docker.io/anusha292/apache-hello:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80