apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-hello
  labels:
    app: apache-hello
  annotations:
    argocd-image-updater.argoproj.io/image-list: apache=anusha292/apache-hello
    argocd-image-updater.argoproj.io/apache.pull-secret: pullsecret:docker-creds
    argocd-image-updater.argoproj.io/apache.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-hello
  template:
    metadata:
      labels:
        app: apache-hello
    spec:
      imagePullSecrets:
        - name: docker-creds
      containers:
        - name: apache
          image: anusha292/apache-hello:latest
          ports:
            - containerPort: 80
