apiVersion: v1
data:
  .dockerconfigjson: YW51c2hhMjkyOlZBYm5nQDIwMjMK
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: apache-hello-app:/Secret:default/docker-creds
  name: docker-creds
  namespace: default
type: kubernetes.io/dockerconfigjson
