name: Build and Push Docker Image

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- Read & increment SemVer ----
      - name: Determine next semantic version
        id: semver
        run: |
          # if VERSION file doesn't exist, create base version
          if [ ! -f VERSION ]; then
            echo "v1.0.0" > VERSION
          fi

          VERSION=$(cat VERSION)

          # extract MAJOR.MINOR.PATCH
          MAJOR=$(echo $VERSION | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # increment PATCH
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$NEW_PATCH"

          echo $NEW_VERSION > VERSION

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # ---- Save updated VERSION file back to repo ----
      # Required for continued increments
      - name: Commit updated VERSION file
        run: |
          git config --global user.email "https://github.com/Anusha-292/"
          git config --global user.name "Anusha-292"
          git add VERSION
          git commit -m "Bump VERSION to ${{ steps.semver.outputs.version }}" || echo "No changes to commit"
          git push

      # ---- Docker buildx ----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- Build and push images ----
      - name: Build and push image with SemVer
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/apache-hello"
          VERSION="${{ steps.semver.outputs.version }}"

          docker build -t $IMAGE:$VERSION .
          docker push $IMAGE:$VERSION

      - name: Tag & Push latest
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/apache-hello"
          VERSION="${{ steps.semver.outputs.version }}"

          docker tag $IMAGE:$VERSION $IMAGE:latest
          docker push $IMAGE:latest
